function Read-LocationHistory {
  <#
  .SYNOPSIS
      List directory traversal history stack
  
  .DESCRIPTION
      ld adds a stack viewer to list the contents of the 'History' stack generated by cd which holds all previous directory locations for reverse traversal

  .NOTES
      New-Alias -Name 'ld' Read-LocationHistory
  .LINK
      Update-Location
  #>
  if ($(Get-Location -StackName "History" -ErrorAction SilentlyContinue)) {
      Get-Location -StackName "History"
  } else {
      Write-Output -InputObject "No path history available"
  }
}